Update to version 1.1.1
conda-forge/bentoml-feedstock pull request #9
Opened 2023-08-09 10:08 UTC by rxm7706

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

2023-08-09 10:08 UTC, rxm7706 commented
@conda-forge-admin, please rerender

2023-11-23 13:33 UTC, rxm7706 commented
@conda-forge-admin, please rerender

2023-11-23 14:02 UTC, rxm7706 commented
@sugatoray @conda-forge/core could you please review and merge - 
I've added myself to the recipe as a maintainers, as there 6 open PRs and current conda pr version is already 9 release behind from pip / source. I will try to help bring this feedstock back to active and current maintenance.

2023-11-23 14:11 UTC, xhochy requested changes

2023-11-23 14:11 UTC, xhochy commented on recipe/meta.yaml
> -    - pip check
You shouldn't remove this.

2023-11-23 14:16 UTC, rxm7706 commented on recipe/meta.yaml
> -    - pip check
Oh I didnt notice that.. thanks for catching that @xhochy 
let me revert, and retest - Not sure why or how that happened, this PR was done 3 months ago.

2023-11-23 14:53 UTC, rxm7706 commented
@conda-forge-admin, please rerender

2023-11-23 15:03 UTC, rxm7706 commented
@conda-forge-admin, please rerender

2023-11-23 15:10 UTC, rxm7706 commented
@xhochy - Ready for review.

2023-11-23 15:20 UTC, sugatoray commented
@rxm7706 Thank you for the PR. Looks good to me. 🚀

2023-11-23 15:20 UTC, xhochy approved these changes

2023-11-23 15:22 UTC, rxm7706 commented
> @rxm7706 Thank you for the PR. Looks good to me. 🚀

Awesome - could you go ahead merge please !

2023-11-23 15:23 UTC, merged